name: Vercel Deployment
env:
  VERCEL_ORG_ID: team_p7m1hVNpQXWK2OtMrjGdFag0
  VERCEL_PROJECT_ID: prj_ahWIMDaqdXn78lRvwTQ9oFEjKdTT
on:
  push:
    branches:
      - main
      - master
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=4CULxheJEMhIGVtL34Uhhdq1
      - name: Build Project Artifacts
        run: vercel build --prod --token=4CULxheJEMhIGVtL34Uhhdq1
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=4CULxheJEMhIGVtL34Uhhdq1
